/* Generated by BOLTS, do not modify */
/* Copyright by: Johannes Reinhardt <jreinhardt@ist-dein-freund.de> */
/* MIT <http://opensource.org/licenses/MIT> */
function roundBattery_table_0(key) = 
//h, d
key == "AA" ? [50.5, 14.5] : 
key == "A" ? [50.0, 17.0] : 
key == "C" ? [50.0, 26.2] : 
key == "AAA" ? [44.5, 10.5] : 
key == "D" ? [61.5, 34.2] : 
key == "N" ? [30.2, 12.0] : 
key == "AAAA" ? [42.5, 8.3] : 
key == "Sub-C" ? [42.9, 22.2] : 
key == "1/2AA" ? [24.0, 14.5] : 
"Error";

